### PR TITLE
Check system prefix

### PR DESCRIPTION
**Pull request by jakirkham**
Also search for libraries and includes in the system prefix.

### CODE REVIEW

**Comment by peterjc** [comment]
Is this needed when Python has been installed in a non-standard location? The code change (and indentation) looks fine.

**Comment by jakirkham** [comment]
I needed it to build with `conda` where `lib` and `include` are the same for Python and everything else installed and can be easily found using `sys.prefix`. These end up being in non-standard locations as it is wherever the user installed `conda`.

Non-framework builds of Python should be the same on Mac. For framework builds of Python on Mac, these are places to search of Python's `include` and `lib` directory, but nothing else will be found there. FWICT this should always work on Linux.

The only point that might be worth discussing is the order these are placed in. It might be worth placing this prefix before the home directory, but did not know what you thought about this.

**Comment by peterjc** [comment]
I would imagine any copy of Python under the user's home directory should be given priority. Thanks for the explanation.

**Comment by jakirkham** [comment]
Certainly see that point.

Just thought it would be worth mentioning that it seems preferable to pick up the `libpython` associated with the interpreter doing the install before searching elsewhere.

Also using the same `liblzma` used by Python 3 when doing that sort of install. Though that use case may be less common.

**Comment by peterjc** [comment]
So you'd put ``sys.prefix`` first?

**Comment by jakirkham** [comment]
That is my thinking at least. Does that seem reasonable to you?

**Comment by peterjc** [comment]
It sounds reasonable, but I'm not familiar enough with this to have a strong view. Pull request to switch order?

**Comment by jakirkham** [comment]
Sure. Please see PR ( https://github.com/peterjc/backports.lzma/pull/20 ).

**Pull request merged**
