### PR TITLE
Fix for 0 max_block_size in constructor and reads spanning block boundries

### PR DESCRIPTION
**Pull request by up2l8**

### CODE REVIEW

**Comment by peterjc** [comment]
What exactly is the bug you are fixing? Is there a test case? Is there a matching upstream bug report? If not, assuming the latest standard library is also broken, please report the problem and add a link the bug report here. Thanks!

**Comment by up2l8** [comment]
Was playing with your random access reader class and found a couple of trivial bugs.  Nothing wrong with the standard library that I know of and this code (bxzf.py) wasn't on the master branch.

**Comment by up2l8** [comment]
The bugs were:
1. The XzReader constructor was not properly handling max_block_size of 0.
2. The read() method was not resetting the internal block offset when a new block was read.

**Comment by peterjc** [comment]
Sorry, I missed you were looking at the branch - I've not been using that code recently.

**Comment by peterjc** [comment]
I'm about to archive this repository, and so am closing the outstanding issues and pull requests. Thank you for your efforts though.

**Pull request closed without merging**
